version: "3.8"
services:
    frontend:
        container_name: frontend
        build: ./frontend
        ports:
            - '5173:5173'
        volumes: 
            - ./frontend:/frontend
            - /frontend/node_modules